name: TechFun
version: 0.0.6
main: me.KodingKing1.TechFun.TechFunMain
author: KodingKing1
commands:
  tf:
    usage: /<command> [Sub-Command]
    description: The main command of TechFun!
    aliases: [TechFun]